### ISSUE TITLE
带?通配符的搜索结果不能正确高亮

### ISSUE THREAD

**Issue by solymr** [easynet-cn/jquery-highlight#1]
*（星号）通配符没有问题了，但是?（问号）通配符的搜索结果仍然不能高亮。如图所示，搜索策略分别为：ti=car?，ti=syst?m：
![image](https://cloud.githubusercontent.com/assets/10542611/5753155/26b7bb88-9cbf-11e4-96fb-b2e4e3973e3a.png)
![image](https://cloud.githubusercontent.com/assets/10542611/5753162/6c94e7a2-9cbf-11e4-8244-e399023852e2.png)

**Comment by easynet-cn** [comment]
已修正。

**Comment by solymr** [comment]
测试通过
